#############################################################################
# Makefile for building: DCCrypt
# Generated by qmake (2.01a) (Qt 4.7.0) on: Fr. Jul 22 19:47:01 2011
# Project:  DCCrypt.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile DCCrypt.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = aboutdialog.cpp \
		checkforupdatesdialog.cpp \
		createkey.cpp \
		createkeydialog.cpp \
		dialog.cpp \
		encryptdecryptfile.cpp \
		encryptdecryptfilewithpass.cpp \
		encryptdecryptfolder.cpp \
		encryptdecryptfolderwithpass.cpp \
		fileencryptdecryptdialog.cpp \
		folderencryptdecryptdialog.cpp \
		main.cpp \
		settingsdialog.cpp moc_aboutdialog.cpp \
		moc_checkforupdatesdialog.cpp \
		moc_createkey.cpp \
		moc_createkeydialog.cpp \
		moc_dialog.cpp \
		moc_encryptdecryptfile.cpp \
		moc_encryptdecryptfilewithpass.cpp \
		moc_encryptdecryptfolder.cpp \
		moc_encryptdecryptfolderwithpass.cpp \
		moc_fileencryptdecryptdialog.cpp \
		moc_folderencryptdecryptdialog.cpp \
		moc_settingsdialog.cpp \
		qrc_resources.cpp
OBJECTS       = aboutdialog.o \
		checkforupdatesdialog.o \
		createkey.o \
		createkeydialog.o \
		dialog.o \
		encryptdecryptfile.o \
		encryptdecryptfilewithpass.o \
		encryptdecryptfolder.o \
		encryptdecryptfolderwithpass.o \
		fileencryptdecryptdialog.o \
		folderencryptdecryptdialog.o \
		main.o \
		settingsdialog.o \
		moc_aboutdialog.o \
		moc_checkforupdatesdialog.o \
		moc_createkey.o \
		moc_createkeydialog.o \
		moc_dialog.o \
		moc_encryptdecryptfile.o \
		moc_encryptdecryptfilewithpass.o \
		moc_encryptdecryptfolder.o \
		moc_encryptdecryptfolderwithpass.o \
		moc_fileencryptdecryptdialog.o \
		moc_folderencryptdecryptdialog.o \
		moc_settingsdialog.o \
		qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		DCCrypt.pro
QMAKE_TARGET  = DCCrypt
DESTDIR       = 
TARGET        = DCCrypt

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_aboutdialog.h ui_checkforupdatesdialog.h ui_createkeydialog.h ui_dialog.h ui_fileencryptdecryptdialog.h ui_folderencryptdecryptdialog.h ui_settingsdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DCCrypt.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile DCCrypt.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile DCCrypt.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/DCCrypt1.0.0 || $(MKDIR) .tmp/DCCrypt1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/DCCrypt1.0.0/ && $(COPY_FILE) --parents aboutdialog.h checkforupdatesdialog.h createkey.h createkeydialog.h dialog.h encryptdecryptfile.h encryptdecryptfilewithpass.h encryptdecryptfolder.h encryptdecryptfolderwithpass.h fileencryptdecryptdialog.h folderencryptdecryptdialog.h settingsdialog.h .tmp/DCCrypt1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/DCCrypt1.0.0/ && $(COPY_FILE) --parents aboutdialog.cpp checkforupdatesdialog.cpp createkey.cpp createkeydialog.cpp dialog.cpp encryptdecryptfile.cpp encryptdecryptfilewithpass.cpp encryptdecryptfolder.cpp encryptdecryptfolderwithpass.cpp fileencryptdecryptdialog.cpp folderencryptdecryptdialog.cpp main.cpp settingsdialog.cpp .tmp/DCCrypt1.0.0/ && $(COPY_FILE) --parents aboutdialog.ui checkforupdatesdialog.ui createkeydialog.ui dialog.ui fileencryptdecryptdialog.ui folderencryptdecryptdialog.ui settingsdialog.ui .tmp/DCCrypt1.0.0/ && $(COPY_FILE) --parents dccrypt_de.ts .tmp/DCCrypt1.0.0/ && (cd `dirname .tmp/DCCrypt1.0.0` && $(TAR) DCCrypt1.0.0.tar DCCrypt1.0.0 && $(COMPRESS) DCCrypt1.0.0.tar) && $(MOVE) `dirname .tmp/DCCrypt1.0.0`/DCCrypt1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/DCCrypt1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_aboutdialog.cpp moc_checkforupdatesdialog.cpp moc_createkey.cpp moc_createkeydialog.cpp moc_dialog.cpp moc_encryptdecryptfile.cpp moc_encryptdecryptfilewithpass.cpp moc_encryptdecryptfolder.cpp moc_encryptdecryptfolderwithpass.cpp moc_fileencryptdecryptdialog.cpp moc_folderencryptdecryptdialog.cpp moc_settingsdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aboutdialog.cpp moc_checkforupdatesdialog.cpp moc_createkey.cpp moc_createkeydialog.cpp moc_dialog.cpp moc_encryptdecryptfile.cpp moc_encryptdecryptfilewithpass.cpp moc_encryptdecryptfolder.cpp moc_encryptdecryptfolderwithpass.cpp moc_fileencryptdecryptdialog.cpp moc_folderencryptdecryptdialog.cpp moc_settingsdialog.cpp
moc_aboutdialog.cpp: aboutdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aboutdialog.h -o moc_aboutdialog.cpp

moc_checkforupdatesdialog.cpp: checkforupdatesdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) checkforupdatesdialog.h -o moc_checkforupdatesdialog.cpp

moc_createkey.cpp: createkey.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) createkey.h -o moc_createkey.cpp

moc_createkeydialog.cpp: createkeydialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) createkeydialog.h -o moc_createkeydialog.cpp

moc_dialog.cpp: dialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_encryptdecryptfile.cpp: encryptdecryptfile.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) encryptdecryptfile.h -o moc_encryptdecryptfile.cpp

moc_encryptdecryptfilewithpass.cpp: encryptdecryptfilewithpass.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) encryptdecryptfilewithpass.h -o moc_encryptdecryptfilewithpass.cpp

moc_encryptdecryptfolder.cpp: encryptdecryptfile.h \
		encryptdecryptfolder.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) encryptdecryptfolder.h -o moc_encryptdecryptfolder.cpp

moc_encryptdecryptfolderwithpass.cpp: encryptdecryptfilewithpass.h \
		encryptdecryptfolderwithpass.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) encryptdecryptfolderwithpass.h -o moc_encryptdecryptfolderwithpass.cpp

moc_fileencryptdecryptdialog.cpp: fileencryptdecryptdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fileencryptdecryptdialog.h -o moc_fileencryptdecryptdialog.cpp

moc_folderencryptdecryptdialog.cpp: folderencryptdecryptdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) folderencryptdecryptdialog.h -o moc_folderencryptdecryptdialog.cpp

moc_settingsdialog.cpp: settingsdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) settingsdialog.h -o moc_settingsdialog.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		resources/images/DCCrypt_Logo.png
	/usr/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_aboutdialog.h ui_checkforupdatesdialog.h ui_createkeydialog.h ui_dialog.h ui_fileencryptdecryptdialog.h ui_folderencryptdecryptdialog.h ui_settingsdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_aboutdialog.h ui_checkforupdatesdialog.h ui_createkeydialog.h ui_dialog.h ui_fileencryptdecryptdialog.h ui_folderencryptdecryptdialog.h ui_settingsdialog.h
ui_aboutdialog.h: aboutdialog.ui
	/usr/bin/uic-qt4 aboutdialog.ui -o ui_aboutdialog.h

ui_checkforupdatesdialog.h: checkforupdatesdialog.ui
	/usr/bin/uic-qt4 checkforupdatesdialog.ui -o ui_checkforupdatesdialog.h

ui_createkeydialog.h: createkeydialog.ui
	/usr/bin/uic-qt4 createkeydialog.ui -o ui_createkeydialog.h

ui_dialog.h: dialog.ui
	/usr/bin/uic-qt4 dialog.ui -o ui_dialog.h

ui_fileencryptdecryptdialog.h: fileencryptdecryptdialog.ui
	/usr/bin/uic-qt4 fileencryptdecryptdialog.ui -o ui_fileencryptdecryptdialog.h

ui_folderencryptdecryptdialog.h: folderencryptdecryptdialog.ui
	/usr/bin/uic-qt4 folderencryptdecryptdialog.ui -o ui_folderencryptdecryptdialog.h

ui_settingsdialog.h: settingsdialog.ui
	/usr/bin/uic-qt4 settingsdialog.ui -o ui_settingsdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

aboutdialog.o: aboutdialog.cpp aboutdialog.h \
		ui_aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutdialog.o aboutdialog.cpp

checkforupdatesdialog.o: checkforupdatesdialog.cpp checkforupdatesdialog.h \
		ui_checkforupdatesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o checkforupdatesdialog.o checkforupdatesdialog.cpp

createkey.o: createkey.cpp createkey.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o createkey.o createkey.cpp

createkeydialog.o: createkeydialog.cpp createkeydialog.h \
		ui_createkeydialog.h \
		createkey.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o createkeydialog.o createkeydialog.cpp

dialog.o: dialog.cpp dialog.h \
		ui_dialog.h \
		fileencryptdecryptdialog.h \
		folderencryptdecryptdialog.h \
		createkeydialog.h \
		settingsdialog.h \
		aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

encryptdecryptfile.o: encryptdecryptfile.cpp encryptdecryptfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encryptdecryptfile.o encryptdecryptfile.cpp

encryptdecryptfilewithpass.o: encryptdecryptfilewithpass.cpp encryptdecryptfilewithpass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encryptdecryptfilewithpass.o encryptdecryptfilewithpass.cpp

encryptdecryptfolder.o: encryptdecryptfolder.cpp encryptdecryptfolder.h \
		encryptdecryptfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encryptdecryptfolder.o encryptdecryptfolder.cpp

encryptdecryptfolderwithpass.o: encryptdecryptfolderwithpass.cpp encryptdecryptfolderwithpass.h \
		encryptdecryptfilewithpass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encryptdecryptfolderwithpass.o encryptdecryptfolderwithpass.cpp

fileencryptdecryptdialog.o: fileencryptdecryptdialog.cpp fileencryptdecryptdialog.h \
		ui_fileencryptdecryptdialog.h \
		encryptdecryptfile.h \
		encryptdecryptfilewithpass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileencryptdecryptdialog.o fileencryptdecryptdialog.cpp

folderencryptdecryptdialog.o: folderencryptdecryptdialog.cpp folderencryptdecryptdialog.h \
		ui_folderencryptdecryptdialog.h \
		encryptdecryptfolder.h \
		encryptdecryptfile.h \
		encryptdecryptfolderwithpass.h \
		encryptdecryptfilewithpass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o folderencryptdecryptdialog.o folderencryptdecryptdialog.cpp

main.o: main.cpp dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

settingsdialog.o: settingsdialog.cpp settingsdialog.h \
		ui_settingsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsdialog.o settingsdialog.cpp

moc_aboutdialog.o: moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutdialog.o moc_aboutdialog.cpp

moc_checkforupdatesdialog.o: moc_checkforupdatesdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_checkforupdatesdialog.o moc_checkforupdatesdialog.cpp

moc_createkey.o: moc_createkey.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_createkey.o moc_createkey.cpp

moc_createkeydialog.o: moc_createkeydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_createkeydialog.o moc_createkeydialog.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_encryptdecryptfile.o: moc_encryptdecryptfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_encryptdecryptfile.o moc_encryptdecryptfile.cpp

moc_encryptdecryptfilewithpass.o: moc_encryptdecryptfilewithpass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_encryptdecryptfilewithpass.o moc_encryptdecryptfilewithpass.cpp

moc_encryptdecryptfolder.o: moc_encryptdecryptfolder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_encryptdecryptfolder.o moc_encryptdecryptfolder.cpp

moc_encryptdecryptfolderwithpass.o: moc_encryptdecryptfolderwithpass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_encryptdecryptfolderwithpass.o moc_encryptdecryptfolderwithpass.cpp

moc_fileencryptdecryptdialog.o: moc_fileencryptdecryptdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fileencryptdecryptdialog.o moc_fileencryptdecryptdialog.cpp

moc_folderencryptdecryptdialog.o: moc_folderencryptdecryptdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_folderencryptdecryptdialog.o moc_folderencryptdecryptdialog.cpp

moc_settingsdialog.o: moc_settingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsdialog.o moc_settingsdialog.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

